import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactQueryProvider, ReactSessionProvider } from "@/utils";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Suspense } from "react";
import "./globals.css";
import { Navbar } from "@/components/client";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ReactSessionProvider>

        <ReactQueryProvider>
        <Suspense fallback={<div>Loading...</div>}>
            
            {children}
        <ToastContainer />
        </Suspense>
        </ReactQueryProvider>
        </ReactSessionProvider>

      </body>
    </html>
  );
}
